# Generated by Django 5.2.10 on 2026-01-10 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название корма')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('food_type', models.CharField(choices=[('dry', 'Сухой корм'), ('wet', 'Влажный корм'), ('natural', 'Натуральное питание'), ('mixed', 'Смешанное')], max_length=20, verbose_name='Тип корма')),
                ('calories', models.FloatField(verbose_name='Калорийность (ккал/100г)')),
                ('protein', models.FloatField(verbose_name='Белок (%)')),
                ('fat', models.FloatField(verbose_name='Жир (%)')),
                ('fiber', models.FloatField(verbose_name='Клетчатка (%)')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена (руб/кг)')),
                ('suitable_for', models.CharField(help_text='Например: собаки крупных пород, котята', max_length=100, verbose_name='Подходит для')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('pet_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('rabbit', 'Кролик'), ('bird', 'Птица'), ('other', 'Другое')], max_length=20, verbose_name='Вид животного')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('age', models.IntegerField(verbose_name='Возраст (лет)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('activity_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Уровень активности')),
                ('goal', models.CharField(choices=[('weight_loss', 'Похудение'), ('weight_gain', 'Набор веса'), ('maintenance', 'Поддержание веса'), ('active', 'Активный образ жизни'), ('pregnant', 'Беременность/Лактация')], max_length=20, verbose_name='Цель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
