# Generated by Django 5.2.10 on 2026-01-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(verbose_name='Суточная норма калорий')),
                ('protein_need', models.FloatField(verbose_name='Потребность в белке (г)')),
                ('fat_need', models.FloatField(verbose_name='Потребность в жирах (г)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный план')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_amount', models.FloatField(verbose_name='Суточная норма (г)')),
                ('meal_count', models.IntegerField(default=2, verbose_name='Количество кормлений')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.dietplan')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.food')),
            ],
        ),
        migrations.AddField(
            model_name='dietplan',
            name='recommended_foods',
            field=models.ManyToManyField(through='calculations.FoodRecommendation', to='pets.food', verbose_name='Рекомендуемые корма'),
        ),
    ]
